# Generated by Django 3.2.2 on 2021-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210712_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='link',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
