# Generated by Django 3.2.2 on 2021-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.URLField(blank=True, max_length=240),
        ),
    ]
