# Generated by Django 3.2.2 on 2021-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='catagory',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Category'),
        ),
    ]
